apps/persona/urls.py
from . import views
from django.urls import path
from apps.persona.views import *

app_name = 'persona'

urlpatterns = [

    path( 'registrar', registrarPersona, name = 'registrar_persona'),
    path( 'baja', setBajaPersona, name = 'baja_persona'),
    path( 'listado', personaListView.as_view(), name = 'listado_persona'),
    path( 'detalle/<int:pk>', personaDetailView.as_view(), name = 'detalle_persona'),

    path( 'beneficiario/registrar', registrarBeneficiario, name = 'registrar_beneficiario'),
    path( 'beneficiario/editar', editarBeneficiario, name = 'editar_beneficiario'),
    path( 'beneficiario/listado', beneficiarioListView.as_view(), name = 'listado_beneficiario'),
    path( 'beneficiario/detalle/<int:pk>', beneficiarioDetailView.as_view(), name = 'detalle_beneficiario'),

]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register

    # ADD NEW Routes HERE
    re_path('chaining/', include('smart_selects.urls')),

    path("personas/", include("apps.persona.urls")),
    path("electro/", include("apps.electrodependientes.urls")),
    path("inventario/", include("apps.inventario.urls")),
    path("productos/", include("apps.productos.urls")),

    # Leave `Home.Urls` as last the last line
    path("", include("apps.home.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/persona/models.py
from datetime import datetime
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.validators import int_list_validator

from apps.clasificadores.models import Base, General, Contacto, UbicacionDetallada, EstadoCivil, TipoDiscapacidad, TipoDocumento,TipoParentesco, Genero, ObraSocial

FALSE_TRUE = ((True,'SI'),(False,'NO'))

class Persona(General, Contacto, UbicacionDetallada):

    ### Choices del modelo ###
    TIPO_DNI = (('DU','Documento Único'),('LC','Libreta Cívica'))

    ### Atributos del modelo ###
    documento = models.PositiveIntegerField(verbose_name='Numero de documento',blank=False,null=False,unique=True)
    documento_tipo = models.CharField(verbose_name='Tipo de documento',choices=TIPO_DNI,max_length=2)
    cuit = models.CharField(verbose_name='CUIT / CUIL',blank=True,null=True,unique=True, max_length=15)
    nombre = models.CharField(verbose_name='Nombre',null=False,blank=False,max_length=50)
    apellido = models.CharField(verbose_name='Apellido',null=False,blank=False,max_length=50)
    genero = models.ForeignKey(Genero, verbose_name=("Genero"), on_delete=models.CASCADE)
    fecha_nacimiento = models.DateField(verbose_name='Fecha de nacimiento',null=True,blank=True)
    estado_civil = models.ForeignKey(EstadoCivil,verbose_name='Estado civíl',on_delete=models.CASCADE)

    email = models.EmailField(verbose_name='E-mail de contacto', blank=True, null=True)
    titulo= None
    descripcion= None

    class Meta:
        db_table = 'persona'
        verbose_name = 'Persona'
        verbose_name_plural = ' Personas'
        ordering = ['id']

    def save(self, *args, **kwargs):
        self.nombre = self.nombre.capitalize()
        self.apellido = self.apellido.capitalize()
        super().save(*args, **kwargs)

    def __str__(self):
        return "{}".format( self.nombre +' '+ self.apellido + ' - ' + str(self.documento))

    def get_absolute_url(self):
        return reverse('persona:detalle_persona', kwargs={'pk' : self.pk})

    def getTelefono(self):
        if self.codigo_area_c and self.numero_telefono_c:
            return self.codigo_area_c + self.numero_telefono_c
        else:
            return self.codigo_area_f + self.numero_telefono_f

    def getDireccion(self):
        if self.calle and self.numero:
            if self.numero_departamento:
                return self.calle + " " + self.numero + ", Departamento " + self.numero_departamento
            else:
                return self.calle + " " + self.numero

        if self.tira:
            return "Tira " + self.tira + ", Piso " + self.numero_piso + ", Departamento " + self.numero_departamento

        if self.lote:
            return "Lote " + self.lote + ", Manzana " + self.manzana + ", Parcela " + self.parcela

class Beneficiario(General):

    persona_beneficiaria = models.OneToOneField( Persona, verbose_name='Beneficiario', on_delete=models.CASCADE, unique=True, null=False , blank=False, related_name="beneficiario")
    persona_responsable = models.OneToOneField( Persona, verbose_name='Responsable', on_delete=models.CASCADE,null=False , blank=False, related_name="responsable")
    vinculo = models.ForeignKey(TipoParentesco, on_delete=models.CASCADE)
    discapacidad = models.ForeignKey(TipoDiscapacidad,verbose_name='Discapadidad',on_delete=models.CASCADE,blank=False,null=False)
    permanente = models.BooleanField(verbose_name='¿Es permanente la discapacidad?',choices=FALSE_TRUE,max_length=2,blank=True,null=True)

    cud = models.BooleanField(verbose_name='CUD', choices=FALSE_TRUE)
    fecha_vencimiento_cud = models.DateField(verbose_name='Fecha de vencimiento CUD',blank=True,null=True)
    archivo_cud = models.ImageField(verbose_name='Adjuntar CUD', upload_to='documentacion/beneficiarios/',blank=True,null=True)

    obra_social = models.ForeignKey(ObraSocial,verbose_name='Obra social',on_delete=models.CASCADE,blank=True,null=True)
    nro_afiliado = models.CharField(verbose_name='Numero de afiliado', max_length=25,blank=True,null=True,unique=True)

    descripcion = None
    titulo = None

    class Meta:
        db_table = 'beneficiario'
        verbose_name = 'Beneficiario'
        verbose_name_plural = 'Beneficiarios'
        ordering = ['id']

    def __str__(self):
        return "{}".format(self.persona_beneficiaria)

"""
    Con respecto a la documentación: el beneficiario tendrá asociada documentación para su legajo individual.
"""
class DocumentacionBeneficiario(Base):

    beneficiario = models.ForeignKey(Beneficiario, verbose_name='Beneficiario', on_delete=models.CASCADE, editable= False, blank=True, null=True)
    tipo_documento = models.ForeignKey(TipoDocumento, verbose_name='Tipo de documento', on_delete=models.CASCADE)
    archivo = models.FileField(verbose_name='Adjuntar documentación', upload_to='documentacion/beneficiarios/')
    descripcion= models.CharField(verbose_name= 'Descripción', blank= False, null= False, max_length=80)

    class Meta:
        unique_together = [['beneficiario','tipo_documento', 'archivo']]
        db_table = 'documentacion_beneficiario'
        verbose_name = 'Documentación de Beneficiario'
        verbose_name_plural = 'Documentación de Beneficiarios'
        ordering = ['id']

    def __str__(self):
        return "Beneficiario"

apps/persona/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import permission_required
from django.utils.decorators import method_decorator
from django.db.models import Q, Value, F
from datetime import date, datetime
from django.utils import timezone
from django.http import HttpResponseRedirect

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView

## Imports models
from apps.persona.models import Persona, Beneficiario, DocumentacionBeneficiario
from apps.electrodependientes.models import Electrodependiente
from apps.inventario.models import DetallePrestamo
from apps.clasificadores.models import TipoParentesco

## Imports forms
from apps.persona.forms import PersonaForm, BeneficiarioForm,DocumentacionFormset, PersonaEditForm
from apps.forms import BajasForm, ResponsableEditForm

# Helpers
from apps.helpers import getRoute

@permission_required('persona.add_persona', raise_exception=True)
def registrarPersona(request):

    persona = PersonaForm(usuario = request.user)

    context = {
        'title' : 'Registrar nueva persona',
        'persona': persona,
        'active': True
    }

    if 'confirmar' in request.POST:

        persona = PersonaForm(request.POST, usuario = request.user)

        if persona.is_valid():
            persona.save()
            return redirect('persona:listado_persona')
        else:
            persona = PersonaForm(request.POST, usuario = request.user)

            for field in persona.errors:
                persona[field].field.widget.attrs['class'] += ' is-invalid'

            context['persona'] = persona
            return render(request,'persona/registrar.html', context)

    return render(request,'persona/registrar.html', context)

@method_decorator(permission_required('persona.view_persona', raise_exception=True), name='dispatch')
class personaListView(ListView):
    paginate_by = 15
    model = Persona
    template_name = 'persona/listado.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Crear url con filtros para mantener el paginador
        base_url = self.request.build_absolute_uri('/personas/listado?')
        url = getRoute(self, base_url)

        context["title"] = 'Listado de personas registradas'
        context["url"] = url
        context["segment"] = 'personas listado-personas'
        context["active"] = True
        return context

    def get_queryset(self):

        queryset = Persona.objects.filter(activo = True)

        if 'search' in self.request.GET:
            try:
                queryset = Persona.objects.filter(documento = self.request.GET.get('search'), activo = True)

            except Exception as e:
                queryset = Persona.objects.none()

            return queryset

        return queryset

@method_decorator(permission_required('persona.view_persona', raise_exception=True), name='dispatch')
class personaDetailView(UpdateView):
    model = Persona
    form_class = PersonaEditForm
    template_name = 'persona/detalle.html'

    def get_context_data(self, **kwargs):

        prestamos = DetallePrestamo.objects.filter(
            Q(beneficiario__persona_beneficiaria = self.get_object())|
            Q(electro__persona_electrodependiente = self.get_object())
        ).annotate(restante = F('fecha_devolucion') - Value(date.today())).order_by('regresado', 'restante')

        context = super().get_context_data(**kwargs)
        context["active"] = True
        context["title"] = 'Detalle de persona'
        context["baja_form"] = BajasForm()
        context["prestamos"] = prestamos
        return context

    def form_valid(self, form):
        form.instance.usuario_modificacion = self.request.user.pk
        super().form_valid(form)
        return HttpResponseRedirect(self.get_success_url())

@permission_required('persona.edit_persona', raise_exception=True)
def setBajaPersona(request):

    if 'confirmar' in request.POST:
        persona = Persona.objects.get(pk = request.POST.get('id'))
        persona.activo = False
        persona.usuario_baja = request.user.pk
        persona.fecha_baja = datetime.now(tz=timezone.utc)
        persona.save()

        try:
            electro = Electrodependiente.objects.get(persona_electrodependiente = persona)
            electro.activo = False
            electro.usuario_baja = request.user.pk
            electro.fecha_baja = datetime.now(tz=timezone.utc)
            electro.save()
        except Exception as e:
            pass

        try:
            beneficiario = Beneficiario.objects.get(persona_beneficiaria = persona)
            beneficiario.activo = False
            beneficiario.usuario_baja = request.user.pk
            beneficiario.fecha_baja = datetime.now(tz=timezone.utc)
            beneficiario.save()
        except Exception as e:
            pass

    return redirect('persona:listado_persona')


"""
BENEFICIARIOS
"""
@permission_required('persona.add_beneficiario', raise_exception=True)
def registrarBeneficiario(request):

    beneficiario = BeneficiarioForm(usuario = request.user)
    #documentacion = DocumentacionForm()

    context = {
        'title' : 'Registrar beneficiario',
        'beneficiario': beneficiario,
        'active': True,
        #'documentacion': documentacion
    }

    if 'confirmar' in request.POST:

        beneficiario = BeneficiarioForm(request.POST, request.FILES, usuario = request.user)

        #documentacion = DocumentacionForm(request.POST, request.FILES)
        if beneficiario.is_valid(): #and documentacion.is_valid():
            beneficiario = beneficiario.save()
            # documentacion = documentacion.save(commit = False)
            # documentacion.beneficiario = beneficiario
            # documentacion = documentacion.save()

            return redirect('persona:listado_beneficiario')
        else:
            beneficiario = BeneficiarioForm(request.POST, request.FILES, usuario = request.user)
            #documentacion = DocumentacionForm(request.POST, request.FILES)

            for field in beneficiario.errors:
                beneficiario[field].field.widget.attrs['class'] += ' is-invalid'

            # for field in documentacion.errors:
            #     documentacion[field].field.widget.attrs['class'] += ' is-invalid'

            context['beneficiario'] = beneficiario
            #context['documentacion'] = documentacion
            return render(request,'persona/beneficiario/registrar.html', context)

    return render(request,'persona/beneficiario/registrar.html', context)

@permission_required('persona.edit_beneficiario', raise_exception=True)
def editarBeneficiario(request):

    if 'confirmar_responsable' in request.POST:

        beneficiario = Beneficiario.objects.get(pk = request.POST.get('id'))
        beneficiario.persona_responsable = Persona.objects.get(pk = request.POST.get('responsable'))
        beneficiario.vinculo = TipoParentesco.objects.get(pk = request.POST.get('vinculo'))
        beneficiario.save()

    if 'confirmar_documentacion' in request.POST:
        documentacionFormset = DocumentacionFormset(request.POST, request.FILES)
        if documentacionFormset.is_valid():
            beneficiario = Beneficiario.objects.get(pk = request.POST.get('id'))
            documentos = documentacionFormset.save( commit=False )
            for d in documentos:
                d.beneficiario = beneficiario
                d.save()

    return redirect('persona:detalle_beneficiario', pk=request.POST.get('id'))

@method_decorator(permission_required('persona.view_beneficiario', raise_exception=True), name='dispatch')
class beneficiarioListView(ListView):
    paginate_by = 15
    model = Beneficiario
    template_name = 'persona/beneficiario/listado.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Crear url con filtros para mantener el paginador
        base_url = self.request.build_absolute_uri('/personas/beneficiario/listado?')
        url = getRoute(self, base_url)

        context["title"] = 'Listado de beneficiarios registrados'
        context["url"] = url
        context["segment"] = 'personas listado-beneficiarios'
        context["active"] = True
        return context

    def get_queryset(self):

        queryset = Beneficiario.objects.filter(activo = True)

        if 'search' in self.request.GET:
            try:
                persona = Persona.objects.get(documento = self.request.GET.get('search'), activo = True)
                queryset = Beneficiario.objects.filter(persona_beneficiaria = persona)

            except Exception as e:
                queryset = Beneficiario.objects.none()

            return queryset

        return queryset

@method_decorator(permission_required('persona.view_beneficiario', raise_exception=True), name='dispatch')
class beneficiarioDetailView(DetailView):
    model = Beneficiario
    template_name = 'persona/beneficiario/detalle.html'

    def get_context_data(self, **kwargs):

        prestamos = DetallePrestamo.objects.filter(
            beneficiario__persona_beneficiaria = self.get_object().persona_beneficiaria
        ).annotate(restante = F('fecha_devolucion') - Value(date.today())).order_by('regresado', 'restante')

        documentacionFormset = DocumentacionFormset()

        documentos = DocumentacionBeneficiario.objects.filter(beneficiario = self.get_object())

        context = super().get_context_data(**kwargs)
        context["active"] = True
        context["title"] = 'Detalle de beneficiario'
        context["documentacionFormset"] = documentacionFormset
        context["documentos"] = documentos
        context["responsable_edit_form"] = ResponsableEditForm()
        context["prestamos"] = prestamos
        return context

apps/templates/persona/beneficiario/registrar.html
{% extends 'layouts/base2.html' %}

{% block stylesheets %}
    <link type="text/css" href="{{ ASSETS_ROOT }}/css/custom.css" rel="stylesheet">
{% endblock stylesheets %}

{% block title %}{{title}}{% endblock %}

{% block content %}

    <h5 class="py-4 my-2 container">{{title}}</h5>

    <form id="form" method="POST" enctype="multipart/form-data" class="container">

        <!-- Security token -->
        {% csrf_token %}

        <div class="card border-0 shadow-table border-bottom mb-4">
            <div class="card-header bg-gris">
                <h5 class="my-2">Datos del beneficiario</h5>
            </div>

            <div class="card-body border-0">

                {{ beneficiario.usuario_creador}}

                <div class="row align-items-end mb-4">
                    <div class="form-group col">
                        {{ beneficiario.persona_beneficiaria.errors}}
                        {{ beneficiario.persona_beneficiaria.label_tag}}
                        {{ beneficiario.persona_beneficiaria}}
                    </div>
                    <div class="form-group col">
                        {{ beneficiario.persona_responsable.errors}}
                        {{ beneficiario.persona_responsable.label_tag}}
                        {{ beneficiario.persona_responsable}}
                    </div>
                    <div class="form-group col">
                        {{ beneficiario.vinculo.errors}}
                        {{ beneficiario.vinculo.label_tag}}
                        {{ beneficiario.vinculo}}
                    </div>
                </div>
                <div class="row align-items-end mb-4">
                    <div class="form-group col">
                        {{ beneficiario.discapacidad.errors}}
                        {{ beneficiario.discapacidad.label_tag}}
                        {{ beneficiario.discapacidad}}
                    </div>
                    <div class="form-group col">
                        {{ beneficiario.permanente.errors}}
                        {{ beneficiario.permanente.label_tag}}
                        {{ beneficiario.permanente}}
                    </div>
                </div>
                <div class="row align-items-end mb-4">
                    <div class="form-group col">
                        {{ beneficiario.obra_social.errors}}
                        {{ beneficiario.obra_social.label_tag}}
                        {{ beneficiario.obra_social}}
                    </div>
                    <div class="form-group col">
                        {{ beneficiario.nro_afiliado.errors}}
                        {{ beneficiario.nro_afiliado.label_tag}}
                        {{ beneficiario.nro_afiliado}}
                    </div>
                </div>
                <div class="row align-items-end mb-4">
                    <div class="form-group col">
                        {{ beneficiario.cud.errors}}
                        {{ beneficiario.cud.label_tag}}
                        {{ beneficiario.cud}}
                    </div>
                    <div class="form-group col">
                        {{ beneficiario.fecha_vencimiento_cud.errors}}
                        {{ beneficiario.fecha_vencimiento_cud.label_tag}}
                        {{ beneficiario.fecha_vencimiento_cud}}
                    </div>
                    <div class="form-group col">
                        {{ beneficiario.archivo_cud.errors}}
                        {{ beneficiario.archivo_cud.label_tag}}
                        {{ beneficiario.archivo_cud}}
                    </div>
                </div>
            </div>

        </div>


        {% comment %}
            <div class="card border-0 shadow-table border-bottom my-4">
                <div class="card-header bg-gris">
                    <h5 class="my-2">Documentación del beneficiario</h5>
                </div>

                <div class="card-body border-0">

                    {{documentacion.errors}}

                    <div class="row py-2 align-items-end mb-3">

                        <div class="form-group i-border col">
                            {{ documentacion.tipo_documento.errors}}
                            {{ documentacion.tipo_documento.label_tag}}
                            {{ documentacion.tipo_documento }}
                        </div>
                        <div class="form-group i-border col">
                            {{ documentacion.archivo.errors}}
                            {{ documentacion.archivo.label_tag}}
                            {{ documentacion.archivo }}
                        </div>
                    </div>
                    <div class="row py-2 align-items-end mb-3">

                        <div class="form-group i-border col">
                            {{ documentacion.vencimiento.errors}}
                            {{ documentacion.vencimiento.label_tag}}
                            {{ documentacion.vencimiento }}
                        </div>
                        <div class="form-group i-border col">
                            {{ documentacion.fecha_vencimiento.errors}}
                            {{ documentacion.fecha_vencimiento.label_tag}}
                            {{ documentacion.fecha_vencimiento }}
                        </div>
                    </div>

                </div>
            </div>
        {% endcomment %}

        <input type="submit" name="confirmar" value="Confirmar" class="btn btn-success text-white">
    </form>

{% endblock content %}

{% block javascripts %}

    <script>

        // Select2 para buscador en select

        $(document).ready(function() {

            $('#id_persona_beneficiaria').select2({
                debug: true,
                placeholder: 'Buscar persona',
                selectionCssClass: 'h-select',
                allowClear: true,
                escapeMarkup: function (markup) { return markup; },
                language: {
                    noResults: function () {

                        return "<a href='{% url 'persona:registrar_persona' %}'>Sin resultados - Agregar nueva persona</a>";
                    }
                }
            });

            $('#id_persona_responsable').select2({
                language: 'es',
                placeholder: 'Buscar persona',
                selectionCssClass: 'h-select',
                allowClear: true,
                escapeMarkup: function (markup) { return markup; },
                language: {
                    noResults: function () {

                        return "<a href='{% url 'persona:registrar_persona' %}'>Sin resultados - Agregar nueva persona</a>";
                    }
                }
            });
        });
    </script>

    <script>
        $(document).ready(function() {

            $('#id_vencimiento').change( function(){
                if($(this).val() === 'True'){
                    $('#id_fecha_vencimiento').prop('disabled', false)
                }
                else{
                    $('#id_fecha_vencimiento').prop('value', '')
                    $('#id_fecha_vencimiento').prop('disabled', true)
                }
            });

            $('#id_obra_social').change( function(){

                if($(this).val() === ''){
                    $('#id_nro_afiliado').prop('value', '')
                    $('#id_nro_afiliado').prop('disabled', true)
                }
                else{
                    $('#id_nro_afiliado').prop('disabled', false)
                }
            });

            $('#id_cud').change( function(){
                if($(this).val() === 'True'){
                    $('#id_fecha_vencimiento_cud').prop('disabled', false)
                    $('#id_archivo_cud').prop('disabled', false)
                }
                else{
                    $('#id_fecha_vencimiento_cud').prop('value', '')
                    $('#id_fecha_vencimiento_cud').prop('disabled', true)
                    $('#id_archivo_cud').prop('disabled', true)
                }
            });

        })
    </script>

{% endblock javascripts %}