apps/productos/urls.py
from . import views
from django.urls import path
from apps.productos.views import *
from apps.helpers import getNroSerie, getPrestamo

app_name = 'productos'

urlpatterns = [

    # Productos
    path( 'listado', productosListView.as_view(), name = 'listado_productos'),
    path( 'otorgados', otorgadosListView.as_view(), name = 'listado_otorgados'),
    path( 'baja', bajaProducto, name = 'baja_producto'),

    path( 'nro_serie/<int:articulo>', getNroSerie, name = 'nro_serie'),
    path( 'prestamo/<int:producto>/<int:sucursal>', getPrestamo, name = 'prestamo'),

    # Articulos
    path( 'articulos/crear', createNewArticulo, name = 'crear_articulo'),
    path( 'articulos/listado', ArticulosListView.as_view(), name = 'listado_articulos'),
    path( 'articulos/c_status', articuloChangeState, name = 'change_articulo'),

    # Marcas
    path( 'marcas/crear', createNewMarca, name = 'crear_marca'),
    path( 'marcas/listado', MarcasListView.as_view(), name = 'listado_marcas'),
    path( 'marcas/c_status', marcaChangeState, name = 'change_marca'),

    # Categorias
    path( 'categorias/crear', createNewCategoria, name = 'crear_categoria'),
    path( 'categorias/listado', CategoriasListView.as_view(), name = 'listado_categorias'),
    path( 'categorias/c_status', categoriaChangeState, name = 'change_categoria'),

    #Subcategorias
    path( 'subcategorias/crear', createNewSubcategoria, name = 'crear_subcategoria'),
    path( 'subcategorias/listado', SubcategoriasListView.as_view(), name = 'listado_subcategorias'),
    path( 'subcategorias/c_status', subcategoriaChangeState, name = 'change_subcategoria'),


]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register

    # ADD NEW Routes HERE
    re_path('chaining/', include('smart_selects.urls')),

    path("personas/", include("apps.persona.urls")),
    path("electro/", include("apps.electrodependientes.urls")),
    path("inventario/", include("apps.inventario.urls")),
    path("productos/", include("apps.productos.urls")),

    # Leave `Home.Urls` as last the last line
    path("", include("apps.home.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/templates/articulos/listado_articulos.html
{% extends 'layouts/base2.html' %}

{% block stylesheets %}
    <link type="text/css" href="{{ ASSETS_ROOT }}/css/custom.css" rel="stylesheet">
{% endblock stylesheets %}

{% block title %}{{title}}{% endblock %}

{% block content %}

    <!-- Modal Filter -->
    <div class="modal fade m-modal-7" id="articulos_filter" tabindex="-1" role="dialog" aria-labelledby="articulos_filterTitle" aria-hidden="true">
        <div class="modal-dialog modal-xl modal-dialog-centered" role="document">
            <div class="modal-content">

                <div class="modal-header bg-gris">
                    <h5 class="modal-title" id="exampleModalLongTitle">Filtrar por:</h5>
                </div>

                <form id="filter_form" method="GET" action="{% url 'productos:listado_articulos' %}">
                    <div class="modal-body">

                        404

                        {% comment %}
                        <div class="row align-items-end mb-3">

                            <div class="form-group col">
                                {{ filter_form.articulo.label_tag}}
                                {{ filter_form.articulo}}
                            </div>
                            <div class="form-group col">
                                {{ filter_form.situacion.label_tag}}
                                {{ filter_form.situacion}}
                            </div>
                            <div class="form-group col">
                                {{ filter_form.sucursal.label_tag}}
                                {{ filter_form.sucursal}}
                            </div>
                        </div>
                        <div class="row align-items-end mb-3">
                            <div class="form-group col">
                                {{ filter_form.estado.label_tag}}
                                {{ filter_form.estado}}
                            </div>
                            <div class="form-group col">
                                {{ filter_form.marca.label_tag}}
                                {{ filter_form.marca}}
                            </div>
                            <div class="form-group col">
                                {{ filter_form.origen.label_tag}}
                                {{ filter_form.origen}}
                            </div>
                        </div>
                        <div class="row">
                            <div class="mb-3 col">
                                <div class="d-flex justify-content-center">
                                    <div>
                                        <label for="valor">Valor:</label>

                                        <input type="text" disabled hidden id="valor" name="valor-range"/>
                                        <input type="text" disabled id="valor-text" style="border: 0; color: #f6931f; font-weight: bold;" />

                                        <div id="valor-range" style="width:450px;"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="mb-3 col">
                                <div class="d-flex justify-content-center">
                                    <div>
                                        <label for="modelo">Modelo:</label>
                                        <input type="text" disabled hidden id="modelo" name="modelo-range"/>
                                        <input type="text" disabled id="modelo-text" name="" style="border: 0; color: #f6931f; font-weight: bold;" />
                                        <div id="modelo-range" style="width:450px;"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endcomment %}

                    </div>
                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn border border-danger text-danger" data-bs-dismiss="modal">Cancelar</button>
                        <div>
                            <button id="borrar_filtros" type="button" class="btn border-orange me-2">Borrar filtros</button>
                            <button name="filter" value="true" type="submit" class="btn bg-orange text-white">Aplicar filtros</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Modal Agregar -->
    <div class="modal fade m-modal-7" id="articulos_agregar" tabindex="-1" role="dialog" aria-labelledby="articulos_agregarTitle" aria-hidden="true">
        <div class="modal-dialog modal-xl modal-dialog-centered" role="document">
            <div class="modal-content">

                <div class="modal-header bg-gris">
                    <h5 class="modal-title">Agregar artículo</h5>
                </div>

                <form id="agregar_form" method="POST" action="{% url 'productos:crear_articulo' %}">

                    {% csrf_token %}

                    <div class="modal-body">
                        {{articuloForm.media.js}}
                        {{articuloForm.as_p}}
                    </div>

                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn border border-danger text-danger" data-bs-dismiss="modal">Cancelar</button>
                        <div>
                            <button name="confirmar" value="true" type="submit" class="btn bg-orange text-white">Confirmar</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>

    <!-- Table -->
    <div class="card border-0 shadow-table my-4">

        <div class="card-header d-flex flex-direction-row justify-content-between bg-gris">
            <h5 class="my-auto">{{title}}</h5>

                <div class="d-flex flex-direction-row justify-content-between">

                    <form method="GET" class="me-3" action="{% url 'productos:listado_articulos' %}">
                        <div class="input-group">
                            <input type="text" required class="form-control" id="exampleInputIconRight" name="search" placeholder="Buscar artículo" aria-label="Buscar documento">
                            <button type="submit" class="input-group-text bg-orange" id="basic-addon2"><i class="fa fa-search text-white" aria-hidden="true"></i></a href="#"></button>
                        </div>
                    </form>

                    {% comment %} <button class="btn bg-orange text-white me-3" type="button" data-bs-toggle="modal" data-bs-target="#articulos_filter" aria-expanded="false" aria-controls="articulos_filter">
                        Filtrar
                    </button> {% endcomment %}

                    {% if perms.productos.add_articulo%}
                        <button class="btn bg-success text-white" type="button" data-bs-toggle="modal" data-bs-target="#articulos_agregar" aria-expanded="false" aria-controls="articulos_agregar">
                            Agregar
                        </button>
                    {% endif %}

                </div>
        </div>

        {% if messages %}
            {% for m in messages %}
                <div class="mx-3 mb-0 mt-3">{{m}}</div>
            {% endfor %}
        {% endif %}

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-centered table-nowrap mb-0 rounded">

                    <thead class="thead-light">
                        <tr>
                            <th class="border-0 rounded-start">Titulo</th>
                            <th class="border-0">Categoria</th>
                            <th class="border-0">Subcategoria</th>
                            <th class="border-0 text-center">Electrodependiente</th>
                            <th class="border-0 text-center">Activo</th>
                            <th class="border-0 text-center rounded-end">Activar / Desactivar</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for articulo in object_list %}
                        <tr class="align-middle">
                            <td>
                                {{articulo.titulo}}
                            </td>
                            <td>
                                {{articulo.categoria}}
                            </td>
                            <td class="col-sm-2">
                                {{articulo.subcategoria}}
                            </td>
                            <td class="col-sm-1 text-center">
                                {% if articulo.electrodependientes %}<i class="fa-solid fa-check text-success"></i>{% else %}<strong class="text-danger">-</strong>{% endif %}
                            </td>
                            <td id ="a-{{articulo.pk}}" class="col-sm-2 text-center">
                                {% if articulo.activo %}<i class="fa-solid fa-check text-success"></i>{% else %}<i class="fa-solid fa-xmark text-danger"></i>{% endif %}
                            </td>
                            <td class="col-sm-1 text-center">
                                {% if articulo.activo %}
                                <button class="btn btn-status" type="button" value="{{articulo.pk}}" title="Desactivar"><i class="fa fa-times-circle text-danger" aria-hidden="true"></i></button>
                                {% else %}
                                <button class="btn btn-status" type="button" value="{{articulo.pk}}" title="Activar"><i class="fa fa-check-circle text-success" aria-hidden="true"></i></button>
                                {% endif %}
                            </td>
                        </tr>

                        {% empty %}

                            <tr style="line-height: 6rem;">
                                <td colspan="8" class="text-center">Sin resultados</td>
                            </tr>

                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center li-hover mb-0">

            <li class="page-item">
                <a class="page-link" href="{{url}}page=1" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">First</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="{{url}}page={% if page_obj.has_previous %}{{ page_obj.previous_page_number }}{% endif %}" aria-label="Previous">
                <span aria-hidden="true">&lsaquo;</span>
                <span class="sr-only">Previous</span>
                </a>
            </li>

            {% for i in page_obj.paginator.page_range %}
                <li class="page-item">
                    <a class="page-link {% if page_obj.number == i %}bg-orange text-white{% endif %}" href="{{url}}page={{ i }}">{{i}}</a>
                </li>
            {% endfor %}

            <li class="page-item">
                <a class="page-link" href="{{url}}page={% if page_obj.has_next %}{{ page_obj.next_page_number }}{% endif %}" aria-label="Next">
                <span aria-hidden="true">&rsaquo;</span>
                <span class="sr-only">Next</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="{{url}}page={% if page_obj.has_next %}{{ page_obj.paginator.num_pages }}{% endif %}" aria-label="Previous">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Last</span>
                </a>
            </li>
        </ul>
    </nav>

{% endblock content %}

{% block javascripts %}


    <script>
        $(document).ready(()=>{

            $('.btn-status').click(function(){

                let id = this.value
                let btn = this

                $.post( '/productos/articulos/c_status', { id : id }
                )
                .done(function( data ) {

                    if(data['status']){
                        $('#a-' + id ).empty().append('<i class="fa-solid fa-check text-success"></i>')
                        $(btn).empty().append('<i class="fa fa-times-circle text-danger" aria-hidden="true"></i>')
                        $(btn).prop('title', 'Desactivar')
                    }
                    else{
                        $('#a-' + id ).empty().append('<i class="fa-solid fa-xmark text-danger"></i>')
                        $(btn).empty().append('<i class="fa fa-check-circle text-success" aria-hidden="true"></i>')
                        $(btn).prop('title', 'Activar')
                    }
                })
                .fail(function() {
                    alert( "server error" );
                })

            })

        });
    </script>


{% endblock javascripts %}

apps/templates/articulos/listado_categorias.html
{% extends 'layouts/base2.html' %}

{% block stylesheets %}
    <link type="text/css" href="{{ ASSETS_ROOT }}/css/custom.css" rel="stylesheet">
{% endblock stylesheets %}

{% block title %}{{title}}{% endblock %}

{% block content %}

    <!-- Modal Agregar -->
    <div class="modal fade m-modal-7" id="categorias_agregar" tabindex="-1" role="dialog" aria-labelledby="categorias_agregarTitle" aria-hidden="true">
        <div class="modal-dialog modal-xl modal-dialog-centered" role="document">
            <div class="modal-content">

                <div class="modal-header bg-gris">
                    <h5 class="modal-title">Agregar categoria</h5>
                </div>

                <form id="agregar_form" method="POST" action="{% url 'productos:crear_categoria' %}">

                    {% csrf_token %}

                    <div class="modal-body">
                        {{categoriaForm.media.js}}
                        {{categoriaForm.as_p}}
                    </div>

                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn border border-danger text-danger" data-bs-dismiss="modal">Cancelar</button>
                        <div>
                            <button name="confirmar" value="true" type="submit" class="btn bg-orange text-white">Confirmar</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>

    <!-- Table -->
    <div class="card border-0 shadow-table my-4">

        <div class="card-header d-flex flex-direction-row justify-content-between bg-gris">
            <h5 class="my-auto">{{title}}</h5>

                <div class="d-flex flex-direction-row justify-content-between">

                    <form method="GET" class="me-3" action="{% url 'productos:listado_categorias' %}">
                        <div class="input-group">
                            <input type="text" required class="form-control" id="exampleInputIconRight" name="search" placeholder="Buscar categoria" aria-label="Buscar categoria">
                            <button type="submit" class="input-group-text bg-orange" id="basic-addon2"><i class="fa fa-search text-white" aria-hidden="true"></i></button>
                        </div>
                    </form>

                    {% if perms.productos.add_categoria%}
                        <button class="btn bg-success text-white" type="button" data-bs-toggle="modal" data-bs-target="#categorias_agregar" aria-expanded="false" aria-controls="categorias_agregar">
                            Agregar
                        </button>
                    {% endif %}

                </div>
        </div>

        {% if messages %}
            {% for m in messages %}
                <div class="mx-3 mb-0 mt-3">{{m}}</div>
            {% endfor %}
        {% endif %}

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-centered table-nowrap mb-0 rounded">

                    <thead class="thead-light">
                        <tr>
                            <th class="border-0 rounded-start">Titulo</th>
                            <th class="border-0 text-center">Activo</th>
                            <th class="border-0 text-center rounded-end">Activar / Desactivar</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for categoria in object_list %}
                        <tr class="align-middle">
                            <td>
                                {{categoria.titulo}}
                            </td>
                            <td id ="a-{{categoria.pk}}" class="text-center">
                                {% if categoria.activo %}<i class="fa-solid fa-check text-success"></i>{% else %}<i class="fa-solid fa-xmark text-danger"></i>{% endif %}
                            </td>
                            <td class="col-sm-1 text-center">
                                {% if categoria.activo %}
                                <button class="btn btn-status py-1 px-2" type="button" value="{{categoria.pk}}" title="Desactivar"><i class="fa fa-times-circle text-danger" aria-hidden="true"></i></button>
                                {% else %}
                                <button class="btn btn-status py-1 px-2" type="button" value="{{categoria.pk}}" title="Activar"><i class="fa fa-check-circle text-success" aria-hidden="true"></i></button>
                                {% endif %}
                            </td>
                        </tr>

                        {% empty %}

                            <tr style="line-height: 6rem;">
                                <td colspan="8" class="text-center">Sin resultados</td>
                            </tr>

                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center li-hover mb-0">

            <li class="page-item">
                <a class="page-link" href="{{url}}page=1" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">First</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="{{url}}page={% if page_obj.has_previous %}{{ page_obj.previous_page_number }}{% endif %}" aria-label="Previous">
                <span aria-hidden="true">&lsaquo;</span>
                <span class="sr-only">Previous</span>
                </a>
            </li>

            {% for i in page_obj.paginator.page_range %}
                <li class="page-item">
                    <a class="page-link {% if page_obj.number == i %}bg-orange text-white{% endif %}" href="{{url}}page={{ i }}">{{i}}</a>
                </li>
            {% endfor %}

            <li class="page-item">
                <a class="page-link" href="{{url}}page={% if page_obj.has_next %}{{ page_obj.next_page_number }}{% endif %}" aria-label="Next">
                <span aria-hidden="true">&rsaquo;</span>
                <span class="sr-only">Next</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="{{url}}page={% if page_obj.has_next %}{{ page_obj.paginator.num_pages }}{% endif %}" aria-label="Previous">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Last</span>
                </a>
            </li>
        </ul>
    </nav>

{% endblock content %}

{% block javascripts %}


    <script>
        $(document).ready(()=>{

            $('.btn-status').click(function(){

                let id = this.value
                let btn = this

                $.post( '/productos/categorias/c_status', { id : id }
                )
                .done(function( data ) {

                    if(data['status']){
                        $('#a-' + id ).empty().append('<i class="fa-solid fa-check text-success"></i>')
                        $(btn).empty().append('<i class="fa fa-times-circle text-danger" aria-hidden="true"></i>')
                        $(btn).prop('title', 'Desactivar')
                    }
                    else{
                        $('#a-' + id ).empty().append('<i class="fa-solid fa-xmark text-danger"></i>')
                        $(btn).empty().append('<i class="fa fa-check-circle text-success" aria-hidden="true"></i>')
                        $(btn).prop('title', 'Activar')
                    }
                })
                .fail(function() {
                    alert( "server error" );
                })

            })

        });
    </script>


{% endblock javascripts %}

apps/templates/articulos/listado_marcas.html
{% extends 'layouts/base2.html' %}

{% block stylesheets %}
    <link type="text/css" href="{{ ASSETS_ROOT }}/css/custom.css" rel="stylesheet">
{% endblock stylesheets %}

{% block title %}{{title}}{% endblock %}

{% block content %}

    <!-- Modal Agregar -->
    <div class="modal fade m-modal-7" id="marcas_agregar" tabindex="-1" role="dialog" aria-labelledby="marcas_agregarTitle" aria-hidden="true">
        <div class="modal-dialog modal-xl modal-dialog-centered" role="document">
            <div class="modal-content">

                <div class="modal-header bg-gris">
                    <h5 class="modal-title">Agregar marca</h5>
                </div>

                <form id="agregar_form" method="POST" action="{% url 'productos:crear_marca' %}">

                    {% csrf_token %}

                    <div class="modal-body">
                        {{marcaForm.media.js}}
                        {{marcaForm.as_p}}
                    </div>

                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn border border-danger text-danger" data-bs-dismiss="modal">Cancelar</button>
                        <div>
                            <button name="confirmar" value="true" type="submit" class="btn bg-orange text-white">Confirmar</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>

    <!-- Table -->
    <div class="card border-0 shadow-table my-4">

        <div class="card-header d-flex flex-direction-row justify-content-between bg-gris">
            <h5 class="my-auto">{{title}}</h5>

                <div class="d-flex flex-direction-row justify-content-between">

                    <form method="GET" class="me-3" action="{% url 'productos:listado_marcas' %}">
                        <div class="input-group">
                            <input type="text" required class="form-control" id="exampleInputIconRight" name="search" placeholder="Buscar marca" aria-label="Buscar marca">
                            <button type="submit" class="input-group-text bg-orange" id="basic-addon2"><i class="fa fa-search text-white" aria-hidden="true"></i></button>
                        </div>
                    </form>

                    {% if perms.productos.add_marca%}
                        <button class="btn bg-success text-white" type="button" data-bs-toggle="modal" data-bs-target="#marcas_agregar" aria-expanded="false" aria-controls="marcas_agregar">
                            Agregar
                        </button>
                    {% endif %}

                </div>
        </div>

        {% if messages %}
            {% for m in messages %}
                <div class="mx-3 mb-0 mt-3">{{m}}</div>
            {% endfor %}
        {% endif %}

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-centered table-nowrap mb-0 rounded">

                    <thead class="thead-light">
                        <tr>
                            <th class="border-0 rounded-start">Titulo</th>
                            <th class="border-0 text-center">Activo</th>
                            <th class="border-0 text-center rounded-end">Activar / Desactivar</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for marca in object_list %}
                        <tr class="align-middle">
                            <td>
                                {{marca.titulo}}
                            </td>
                            <td id ="a-{{marca.pk}}" class="text-center">
                                {% if marca.activo %}<i class="fa-solid fa-check text-success"></i>{% else %}<i class="fa-solid fa-xmark text-danger"></i>{% endif %}
                            </td>
                            <td class="col-sm-1 text-center">
                                {% if marca.activo %}
                                <button class="btn btn-status py-1 px-2" type="button" value="{{marca.pk}}" title="Desactivar"><i class="fa fa-times-circle text-danger" aria-hidden="true"></i></button>
                                {% else %}
                                <button class="btn btn-status py-1 px-2" type="button" value="{{marca.pk}}" title="Activar"><i class="fa fa-check-circle text-success" aria-hidden="true"></i></button>
                                {% endif %}
                            </td>
                        </tr>

                        {% empty %}

                            <tr style="line-height: 6rem;">
                                <td colspan="8" class="text-center">Sin resultados</td>
                            </tr>

                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center li-hover mb-0">

            <li class="page-item">
                <a class="page-link" href="{{url}}page=1" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">First</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="{{url}}page={% if page_obj.has_previous %}{{ page_obj.previous_page_number }}{% endif %}" aria-label="Previous">
                <span aria-hidden="true">&lsaquo;</span>
                <span class="sr-only">Previous</span>
                </a>
            </li>

            {% for i in page_obj.paginator.page_range %}
                <li class="page-item">
                    <a class="page-link {% if page_obj.number == i %}bg-orange text-white{% endif %}" href="{{url}}page={{ i }}">{{i}}</a>
                </li>
            {% endfor %}

            <li class="page-item">
                <a class="page-link" href="{{url}}page={% if page_obj.has_next %}{{ page_obj.next_page_number }}{% endif %}" aria-label="Next">
                <span aria-hidden="true">&rsaquo;</span>
                <span class="sr-only">Next</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="{{url}}page={% if page_obj.has_next %}{{ page_obj.paginator.num_pages }}{% endif %}" aria-label="Previous">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Last</span>
                </a>
            </li>
        </ul>
    </nav>

{% endblock content %}

{% block javascripts %}


    <script>
        $(document).ready(()=>{

            $('.btn-status').click(function(){

                let id = this.value
                let btn = this

                $.post( '/productos/marcas/c_status', { id : id }
                )
                .done(function( data ) {

                    if(data['status']){
                        $('#a-' + id ).empty().append('<i class="fa-solid fa-check text-success"></i>')
                        $(btn).empty().append('<i class="fa fa-times-circle text-danger" aria-hidden="true"></i>')
                        $(btn).prop('title', 'Desactivar')
                    }
                    else{
                        $('#a-' + id ).empty().append('<i class="fa-solid fa-xmark text-danger"></i>')
                        $(btn).empty().append('<i class="fa fa-check-circle text-success" aria-hidden="true"></i>')
                        $(btn).prop('title', 'Activar')
                    }
                })
                .fail(function() {
                    alert( "server error" );
                })

            })

        });
    </script>


{% endblock javascripts %}