apps/electrodependientes/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from apps.electrodependientes.views import *

app_name = 'electrodependientes'

urlpatterns = [

    path( 'registrar', registrarElectro, name = 'registrar_electro'),
    path( 'editar', editarElectro, name = 'editar_electro'),
    path( 'listado', electroListView.as_view(), name = 'listado_electro'),
    path( 'detalle/<int:pk>', electroDetailView.as_view(), name = 'detalle_electro'),

    path( 'medico/registrar', registrarMedico, name = 'registrar_medico'),
    path( 'medico/listado', medicoListView.as_view(), name = 'listado_medico'),

]

apps/home/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from apps.home import views

urlpatterns = [

    # The home page
    path('', views.index, name='home'),

    # Matches any html file
    #re_path(r'^.*\.*', views.pages, name='pages'),

]

apps/persona/urls.py
from . import views
from django.urls import path
from apps.persona.views import *

app_name = 'persona'

urlpatterns = [

    path( 'registrar', registrarPersona, name = 'registrar_persona'),
    path( 'baja', setBajaPersona, name = 'baja_persona'),
    path( 'listado', personaListView.as_view(), name = 'listado_persona'),
    path( 'detalle/<int:pk>', personaDetailView.as_view(), name = 'detalle_persona'),

    path( 'beneficiario/registrar', registrarBeneficiario, name = 'registrar_beneficiario'),
    path( 'beneficiario/editar', editarBeneficiario, name = 'editar_beneficiario'),
    path( 'beneficiario/listado', beneficiarioListView.as_view(), name = 'listado_beneficiario'),
    path( 'beneficiario/detalle/<int:pk>', beneficiarioDetailView.as_view(), name = 'detalle_beneficiario'),

]

apps/productos/urls.py
from . import views
from django.urls import path
from apps.productos.views import *
from apps.helpers import getNroSerie, getPrestamo

app_name = 'productos'

urlpatterns = [

    # Productos
    path( 'listado', productosListView.as_view(), name = 'listado_productos'),
    path( 'otorgados', otorgadosListView.as_view(), name = 'listado_otorgados'),
    path( 'baja', bajaProducto, name = 'baja_producto'),

    path( 'nro_serie/<int:articulo>', getNroSerie, name = 'nro_serie'),
    path( 'prestamo/<int:producto>/<int:sucursal>', getPrestamo, name = 'prestamo'),

    # Articulos
    path( 'articulos/crear', createNewArticulo, name = 'crear_articulo'),
    path( 'articulos/listado', ArticulosListView.as_view(), name = 'listado_articulos'),
    path( 'articulos/c_status', articuloChangeState, name = 'change_articulo'),

    # Marcas
    path( 'marcas/crear', createNewMarca, name = 'crear_marca'),
    path( 'marcas/listado', MarcasListView.as_view(), name = 'listado_marcas'),
    path( 'marcas/c_status', marcaChangeState, name = 'change_marca'),

    # Categorias
    path( 'categorias/crear', createNewCategoria, name = 'crear_categoria'),
    path( 'categorias/listado', CategoriasListView.as_view(), name = 'listado_categorias'),
    path( 'categorias/c_status', categoriaChangeState, name = 'change_categoria'),

    #Subcategorias
    path( 'subcategorias/crear', createNewSubcategoria, name = 'crear_subcategoria'),
    path( 'subcategorias/listado', SubcategoriasListView.as_view(), name = 'listado_subcategorias'),
    path( 'subcategorias/c_status', subcategoriaChangeState, name = 'change_subcategoria'),


]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register

    # ADD NEW Routes HERE
    re_path('chaining/', include('smart_selects.urls')),

    path("personas/", include("apps.persona.urls")),
    path("electro/", include("apps.electrodependientes.urls")),
    path("inventario/", include("apps.inventario.urls")),
    path("productos/", include("apps.productos.urls")),

    # Leave `Home.Urls` as last the last line
    path("", include("apps.home.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/home/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

apps/inventario/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

from apps.productos.models import Producto, Articulo, Marca
from apps.persona.models import Beneficiario
from apps.clasificadores.models import Empresa, Sucursal, PuntoVenta, TipoComprobante
from apps.localizacion.models import Pais
from apps.electrodependientes.models import Electrodependiente

class Numerador(models.Model):
    numeracion = models.IntegerField()
    tipo_comprobante = models.ForeignKey(TipoComprobante, on_delete=models.CASCADE)
    punto_venta = models.ForeignKey(PuntoVenta, on_delete=models.CASCADE)

    class Meta:
        db_table = 'comprobante_numerador'
        verbose_name = 'Numeración de comprobantes'
        verbose_name_plural = 'N° de comprobantes'
        ordering = ['tipo_comprobante']

    def __str__(self):
        return "{} - {} - {}".format( self.tipo_comprobante, self.punto_venta ,  str(self.numeracion).zfill(6) )

class Comprobante(models.Model):

    PROCEDENCIA = (
        ('Adquirido', 'Adquirido'),
        ('Donado', 'Donado'),
        ('Fondo propio', 'Fondo propio')
    )

    numero = models.CharField(max_length=25, blank=True, null=True, editable=False)
    tipo_comprobante = models.ForeignKey(TipoComprobante, on_delete=models.CASCADE, blank=False, null=False)
    sucursal = models.ForeignKey(Sucursal, on_delete=models.CASCADE)
    fecha_operacion = models.DateTimeField(verbose_name='Fecha de operación', default=datetime.now, blank=False, null=False)
    punto_venta = models.ForeignKey(PuntoVenta, on_delete=models.CASCADE, verbose_name='Punto de préstamo', blank=False, null=False)
    procedencia = models.CharField( verbose_name='Procedencia', max_length=20, choices=PROCEDENCIA, blank=True, null=True )
    proveedor = models.ForeignKey(Empresa, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Proveedor')
    descripcion = models.CharField(max_length=50, blank=True, null=True)
    usuario_creador= models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        db_table = 'comprobante'
        verbose_name = 'Comprobante'
        verbose_name_plural = 'Comprobantes'
        ordering = ['id']

    def __str__(self):
        return self.numero

    def save(self):

        try:
            # Aumento el numerador
            numerador = Numerador.objects.get(tipo_comprobante = self.tipo_comprobante, punto_venta = self.punto_venta)
            numerador.numeracion += 1
            numerador.save()

        except Numerador.DoesNotExist:
            # Si no existe un numerador de comprobante se crea uno nuevo
            numerador = Numerador(
                numeracion=1,
                punto_venta = self.punto_venta,
                tipo_comprobante = self.tipo_comprobante
            )
            numerador.save()

        # El N° de comprobante se setea según el punto de venta y tipo de comprobante + Numerador, eg: 'CE USH 01-000001'
        self.numero = f"{self.tipo_comprobante.codigo} {self.punto_venta.codigo}-{str(numerador.numeracion).zfill(6)}"
        super(Comprobante, self).save()

class DetalleEntrada(models.Model):

    modelo_producto = []
    for y in range(2000, (datetime.now().year + 1)):
        modelo_producto.append((y, y))

    ESTADO = (
        ('Nuevo', 'Nuevo'),
        ('Usado', 'Usado'),
        ('Reacondicionado', 'Reacondicionado')
    )

    comprobante = models.ForeignKey(Comprobante, on_delete=models.CASCADE,verbose_name='Nro. de Comprobante')
    articulo = models.ForeignKey(Articulo, on_delete=models.CASCADE, blank=False, null=False)
    marca = models.ForeignKey( Marca, on_delete=models.CASCADE )
    modelo = models.IntegerField( choices=modelo_producto, default=datetime.now().year )
    numero_serie = models.CharField( verbose_name='N° Serie', max_length=15, blank=True, null=True, unique=True )
    pais_origen = models.ForeignKey( Pais, verbose_name='Origen', on_delete=models.CASCADE )
    estado = models.CharField( verbose_name='Estado', max_length=20, choices=ESTADO, blank=False, null=False )
    valor = models.PositiveIntegerField( verbose_name='Valor', blank=False,null=False )

    class Meta:
        db_table = 'comprobante_entradas'
        verbose_name = 'Detalle de Comprobante'
        verbose_name_plural = 'Detalle de Comprobantes'
        ordering = ['id']

    def __str__(self):
        return "{}".format( self.comprobante )

    def save(self):

        try:
            # Productos
            producto = Producto(
                articulo=self.articulo,
                marca=self.marca,
                modelo=self.modelo,
                numero_serie=self.numero_serie,
                origen=self.pais_origen,
                estado=self.estado,
                valor=self.valor,
                situacion='DISP',
                sucursal=self.comprobante.sucursal
            )
            producto.save()

            # Kardex
            kardex = Kardex(
                articulo = self.articulo,
                comprobante= self.comprobante,
                fecha_operacion= self.comprobante.fecha_operacion,
                sucursal= self.comprobante.sucursal,
                cantidad_ingreso = 1,
                cantidad_salida = 0
            )
            kardex_anterior = Kardex.objects.filter(articulo = producto.articulo, sucursal = self.comprobante.sucursal).last()

            # Si no existe un kardex anterior seteo la cantidad total = 1
            kardex.cantidad_total = 1 if not kardex_anterior else kardex_anterior.cantidad_total + 1
        except:
            pass

        super(DetalleEntrada, self).save()
        kardex.save()

class DetallePrestamo(models.Model):
    comprobante = models.ForeignKey(Comprobante, on_delete=models.CASCADE,verbose_name='Nro. de Comprobante', editable=False)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, blank=False, null=False)

    beneficiario = models.ForeignKey(Beneficiario, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Beneficiario')
    electro = models.ForeignKey(Electrodependiente, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Electrodependiente')

    fecha_otorgamiento = models.DateField(verbose_name='Fecha de otorgamiento', blank=False, null=False, default=datetime.now)
    fecha_devolucion = models.DateField(verbose_name='Fecha de devolución', blank=False, null=False, default=None)

    regresado = models.BooleanField(default=False, editable=False)
    baja = models.BooleanField(default=False, editable=False)

    class Meta:
        db_table = 'comprobante_prestamo'
        verbose_name = 'Detalle comprobante de prestamo'
        verbose_name_plural = 'Detalle comprobantes de prestamo'
        ordering = ['id']

    def __str__(self):
        return "{}".format( self.comprobante )

    def save(self):
        try:
            # Producto
            producto = Producto.objects.get(id = self.producto.pk)
            producto.situacion = 'OTO'
            producto.save()

            # Kardex
            kardex_anterior = Kardex.objects.filter(articulo = producto.articulo,sucursal = self.comprobante.sucursal).last()
            kardex = Kardex(
                articulo = producto.articulo,
                comprobante= self.comprobante,
                fecha_operacion= self.comprobante.fecha_operacion,
                sucursal= self.comprobante.sucursal,
                cantidad_ingreso = 0,
                cantidad_salida = 1,
                cantidad_total = kardex_anterior.cantidad_total - 1
            )

        except:
            pass

        super(DetallePrestamo, self).save()
        kardex.save()

class DetalleDevolucion(models.Model):
    comprobante = models.ForeignKey(Comprobante, on_delete=models.CASCADE,verbose_name='Nro. de Comprobante', editable=False)
    comprobante_prestamo = models.OneToOneField(DetallePrestamo, on_delete=models.CASCADE, verbose_name='Comprobante de prestamo', blank=True, null=True, editable=False)
    beneficiario = models.ForeignKey(Beneficiario, on_delete=models.CASCADE, editable=False, blank=True, null=True)
    electro = models.ForeignKey(Electrodependiente, on_delete=models.CASCADE, editable=False, blank=True, null=True)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, verbose_name='Producto')
    fecha_devolucion = models.DateField(verbose_name='Fecha de devolución', blank=False, null=False, default=datetime.now)

    class Meta:
        db_table = 'comprobante_devolucion'
        verbose_name = 'Detalle comprobante de devolución'
        verbose_name_plural = 'Detalle comprobantes de devolución'
        ordering = ['id']

    def __str__(self):
        return "{}".format( self.producto )

    def save(self):

        try:
            # Producto
            producto = Producto.objects.get(id = self.producto.pk)
            producto.situacion = 'DISP'
            producto.save()

            # Prestamo
            prestamo = DetallePrestamo.objects.filter(producto = self.producto.pk, regresado = False)

            # Devolucion - Verifica si el prestamo corresponde a electro o beneficiario -
            self.comprobante_prestamo = prestamo.last()

            if not prestamo.last().beneficiario:
                self.electro = prestamo.last().electro
            else:
                self.beneficiario = prestamo.last().beneficiario

            prestamo = prestamo.update(regresado = True)

            # Kardex
            kardex_anterior = Kardex.objects.filter( articulo = producto.articulo, sucursal = self.comprobante.sucursal).last()
            kardex = Kardex(
                articulo = producto.articulo,
                comprobante= self.comprobante,
                fecha_operacion= self.comprobante.fecha_operacion,
                sucursal= self.comprobante.sucursal,
                cantidad_ingreso = 1,
                cantidad_salida = 0,
                cantidad_total = kardex_anterior.cantidad_total + 1

apps/home/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.template import loader
from django.db.models import Count, Value, F
from django.db.models import IntegerField, Sum, Case, When

from datetime import date

# Import models
from apps.electrodependientes.models import Electrodependiente, Diagnostico
from apps.persona.models import Beneficiario
from apps.productos.models import Producto
from apps.inventario.models import DetallePrestamo

@login_required(login_url="/login/")
def index(request):

    if request.user.has_perm('persona.view_persona'):
        ## Registrados
        electros = Electrodependiente.objects.filter(activo = True).count()
        beneficiarios = Beneficiario.objects.filter(activo = True).count()

        ## Porcentaje disponibilidad
        disponibles = Producto.objects.values('articulo__titulo').order_by('articulo__titulo').exclude(situacion = 'NO_DISP').annotate(count=Count('articulo__titulo'), disponibles = Sum(Case(When(situacion = 'DISP', then = 1),default=0,output_field=IntegerField())))

        for d in disponibles:
            percentaje = (d['disponibles'] * 100) / d['count']
            d['percentaje'] = int(percentaje)

        ## Productos / Electros - fechas de devolución - annotate para incluir campo 'restante' al queryset
        productos_otorgados = DetallePrestamo.objects.filter(regresado = False, baja = False).annotate(restante = F('fecha_devolucion') - Value(date.today())).order_by('restante')[:10]
        electros_vigentes = Diagnostico.objects.filter(activo = True, electrodependiente__activo = True ).annotate(restante = F('fecha_finalizacion') - Value(date.today())).order_by('restante')[:10]

        context = { 'segment': 'inicio','active': True,'electros':electros,'beneficiarios':beneficiarios,'disponibles':disponibles, 'otorgados':productos_otorgados, 'diagnosticos': electros_vigentes }
        html_template = loader.get_template('home/dashboard.html')
    else:
        context = { 'segment': 'inicio','active': False }
        html_template = loader.get_template('home/blank.html')
    return HttpResponse(html_template.render(context, request))


""""
@login_required(login_url="/login/")
def pages(request):
    context = {}
    # All resource paths end in .html.
    # Pick out the html file name from the url. And load that template.
    try:

        load_template = request.path.split('/')[-1]

        if load_template == 'admin':
            return HttpResponseRedirect(reverse('admin:index'))
        context['segment'] = load_template

        html_template = loader.get_template('home/' + load_template)
        return HttpResponse(html_template.render(context, request))

    except template.TemplateDoesNotExist:

        return redirect('home')

    except:
        html_template = loader.get_template('home/page-404.html')
        return HttpResponse(html_template.render(context, request))
"""

apps/templates/home/blank.html
{% extends "layouts/base2.html" %}

{% load l10n %}

{% block title %} Dashboard {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<link type="text/css" href="{{ ASSETS_ROOT }}/css/custom.css" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}

    <h3 class="text-center my-4">Banco de ayuda técnica y registro de Electrodependientes</h3>

    <h5 class="text-center">Solicite los permisos necesarios al administrador para poder acceder a las funciones del sistema</h5>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/dashboard.html
{% extends "layouts/base2.html" %}

{% load l10n %}

{% block title %} Dashboard {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<link type="text/css" href="{{ ASSETS_ROOT }}/css/custom.css" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}

    <h3 class="text-center my-4">Banco de ayuda técnica y registro de Electrodependientes</h3>

    <div class="row mt-4">
        <div class="col-12 col-sm-6 col-xl-6 mb-4">
            <div class="card border-0 shadow-table">
                <div class="card-body">
                    <div class="row d-block d-xl-flex align-items-center py-3">

                        <div class="col-12 col-xl-5 text-xl-center mb-3 mb-xl-0 d-flex align-items-center justify-content-xl-center">
                            <div class="icon-shape icon-shape-primary rounded me-4 me-sm-0">
                                <a href="{% url 'persona:listado_beneficiario' %}">
                                    <i class="fa-solid fa-users fa-2xl"></i>
                                </a>
                            </div>
                            <div class="d-sm-none">
                                <h2 class="fw-extrabold h5">Beneficiarios activos</h2>
                                <h3 class="mb-1">{{beneficiarios}}</h3>
                            </div>
                        </div>
                        <div class="col-12 col-xl-7 px-xl-0">
                            <div class="d-none d-sm-block">
                                <h2 class="h6 text-gray-400 mb-0">Beneficiarios activos</h2>
                                <h3 class="fw-extrabold mb-2">{{beneficiarios}}</h3>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-6 col-xl-6 mb-4">
            <div class="card border-0 shadow-table">
                <div class="card-body">

                    <div class="row d-block d-xl-flex align-items-center py-3">

                        <div class="col-12 col-xl-5 text-xl-center mb-3 mb-xl-0 d-flex align-items-center justify-content-xl-center">
                            <div class="icon-shape icon-shape-danger rounded me-4 me-sm-0">
                                <a href="{% url 'electrodependientes:listado_electro' %}">
                                    <i class="text-danger fa-solid fa-heart-circle-bolt fa-2xl"></i>
                                </a>
                            </div>
                            <div class="d-sm-none">
                                <h2 class="fw-extrabold h5">Electrodependientes activos</h2>
                                <h3 class="mb-1">{{electros}}</h3>
                            </div>
                        </div>
                        <div class="col-12 col-xl-7 px-xl-0">
                            <div class="d-none d-sm-block">
                                <h2 class="h6 text-gray-400 mb-0">Electrodependientes activos</h2>
                                <h3 class="fw-extrabold mb-2">{{electros}}</h3>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12 mb-4">

            <div class="card border-0 shadow-table">

                <div class="card-header bg-gris border-bottom d-flex align-items-center justify-content-between">
                    <h2 class="fs-5 fw-bold mb-0">Disponibilidad de productos</h2>
                    <a href="{% url 'productos:listado_productos' %}" class="btn btn-sm bg-orange text-white">Ver todos</a>
                </div>

                <div class="card-body">

                    {% if disponibles %}
                        {% for p in disponibles|dictsort:"percentaje" %}
                            <div class="row mb-3">
                                <div class="col">
                                    <div class="progress-wrapper">
                                        <div class="progress-info mb-0">
                                            <div class="h6 mb-0 fw-bold">{{p.articulo__titulo}}</div>
                                            <div class="small fw-bold text-gray-500"><span>{{p.disponibles}} de {{p.count}}</span></div>
                                        </div>
                                        <div class="progress mb-0" style="height : 6px!important;">
                                        <div class="progress-bar {% if p.percentaje < 50 %} bg-danger {% elif p.percentaje < 75 %} bg-warning {% else %} bg-success {% endif %}" title="{{p.articulo__titulo}} progressbar" role="progressbar" aria-valuenow={{p.disponible}} aria-valuemin="0" aria-valuemax={{p.count}} style="width: {{p.percentaje}}%;"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <div class="row m-3">
                            No se encontraron productos en el inventario
                        </div>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>

    <div class="row">

        {% if perms.inventario.add_comprobante %}
            <div class="col-12 col-sm-12 col-xl-12 {% if perms.electrodependientes.view_electrodependiente %}col-xxl-6{% endif %} mb-4">
                <div class="card border-0 shadow-table">
                    <div class="card-header bg-gris border-bottom d-flex align-items-center justify-content-between">
                        <h2 class="fs-5 fw-bold mb-0">Productos otorgados</h2>
                        <a href="{% url 'productos:listado_otorgados' %}" class="btn btn-sm bg-orange text-white">Ver todos</a>
                    </div>
                    <div class="card-body table-responsive">

                        <table class="table table-striped table-responsive table-p">
                            <thead>
                            <tr class="text-center">
                                <th scope="col" class="px-0">Beneficiario</th>
                                <th scope="col" class="px-0">Producto</th>
                                <th scope="col" class="px-0">Fecha de devolucion</th>
                                <th scope="col" class="px-0">Tiempo restante</th>
                            </tr>
                            </thead>
                            <tbody>


                                {% for o in otorgados %}
                                    <tr class="text-center">
                                        <td class="fw-bold px-0">

                                            {% if o.beneficiario %}
                                                {{o.beneficiario.persona_beneficiaria.nombre}}
                                                {{o.beneficiario.persona_beneficiaria.apellido}}
                                            {% else %}
                                                {{o.electro.persona_electrodependiente.nombre}}
                                                {{o.electro.persona_electrodependiente.apellido}}
                                            {% endif %}

                                        </td>
                                        <td class="px-0">{{o.producto.articulo}}</td>
                                        <td class="px-0">{{o.fecha_devolucion}}</td>
                                        <td class="fw-bold px-0 {% if o.restante.days < 7 %}text-danger{% elif o.restante.days < 30 %} text-warning{% else %}text-success {% endif %}">
                                            {{o.restante.days}} días
                                        </td>
                                    </tr>
                                {% empty %}

                                    <tr style="line-height: 4rem;">
                                        <td colspan="9" class="text-center">Sin resultados</td>
                                    </tr>

                                {% endfor %}
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        {% endif %}

        {% if perms.electrodependientes.view_electrodependiente %}
            <div class="col-12 col-sm-12 col-xl-12 {% if perms.inventario.add_comprobante %} col-xxl-6 {% endif %} mb-4">
                <div class="card border-0 shadow-table">
                    <div class="card-header bg-gris border-bottom d-flex align-items-center justify-content-between">
                        <h2 class="fs-5 fw-bold mb-0">Electrodependientes vigentes</h2>
                        <a href="{% url 'electrodependientes:listado_electro' %}" class="btn btn-sm bg-orange text-white">Ver todos</a>
                    </div>

                    <div class="card-body table-responsive">

                        <table class="table table-striped table-responsive table-p">
                            <thead>
                            <tr class="text-center">
                                <th scope="col" class="px-0">Electrodepentiente</th>
                                <th scope="col" class="px-0">Fecha diagnostico</th>
                                <th scope="col" class="px-0">Tiempo requerido</th>
                                <th scope="col" class="px-0">Tiempo restante</th>
                            </tr>
                            </thead>
                            <tbody>


                                {% for d in diagnosticos %}
                                    <tr class="text-center">
                                        <td class="fw-bold px-0">
                                            {{d.electrodependiente.persona_electrodependiente.nombre}}
                                            {{d.electrodependiente.persona_electrodependiente.apellido}}
                                        </td>
                                        <td class="px-0">{{d.fecha_diagnostico}}</td>
                                        <td class="px-0">{{d.get_tiempo_requerido_display}}</td>
                                        <td class="fw-bold px-0 {% if d.restante.days <= 30 %}text-danger{% elif d.restante.days <= 90 %} text-warning{% else %}text-success {% endif %}">
                                            {{d.restante.days}} días
                                        </td>

                                    </tr>
                                {% empty %}

                                    <tr style="line-height: 4rem;">
                                        <td colspan="9" class="text-center">Sin resultados</td>
                                    </tr>

                                {% endfor %}
                            </tbody>
                        </table>

                    </div>


                </div>
            </div>
        {% endif %}

    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/page-404.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Sitio en desarrollo - SGD {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}<link type="text/css" href="{{ ASSETS_ROOT }}/css/custom.css" rel="stylesheet">{% endblock stylesheets %}

{% block content %}

    <main>
        <section class="vh-100 d-flex align-items-center justify-content-center">
            <div class="container">
                <div class="row">
                    <div class="col-12 text-center d-flex align-items-center justify-content-center">
                        <div>
                            <img class="img-fluid w-100" src="{{ ASSETS_ROOT }}/img/illustrations/404.svg" alt="404 not found">
                            <h1 class="mt-5">Pagina <span class="fw-bolder text-primary">no encontrada</span></h1>
                            <p class="lead my-4">Secretaría de Gobierno Digital</p>
                            <a href="javascript:history.go(-1)" class="btn bg-orange text-white d-inline-flex align-items-center justify-content-center mb-4">
                                <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.707 14.707a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l2.293 2.293a1 1 0 010 1.414z" clip-rule="evenodd"></path></svg>
                                Volver
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}