apps/electrodependientes/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from apps.electrodependientes.views import *

app_name = 'electrodependientes'

urlpatterns = [

    path( 'registrar', registrarElectro, name = 'registrar_electro'),
    path( 'editar', editarElectro, name = 'editar_electro'),
    path( 'listado', electroListView.as_view(), name = 'listado_electro'),
    path( 'detalle/<int:pk>', electroDetailView.as_view(), name = 'detalle_electro'),

    path( 'medico/registrar', registrarMedico, name = 'registrar_medico'),
    path( 'medico/listado', medicoListView.as_view(), name = 'listado_medico'),

]

apps/persona/urls.py
from . import views
from django.urls import path
from apps.persona.views import *

app_name = 'persona'

urlpatterns = [

    path( 'registrar', registrarPersona, name = 'registrar_persona'),
    path( 'baja', setBajaPersona, name = 'baja_persona'),
    path( 'listado', personaListView.as_view(), name = 'listado_persona'),
    path( 'detalle/<int:pk>', personaDetailView.as_view(), name = 'detalle_persona'),

    path( 'beneficiario/registrar', registrarBeneficiario, name = 'registrar_beneficiario'),
    path( 'beneficiario/editar', editarBeneficiario, name = 'editar_beneficiario'),
    path( 'beneficiario/listado', beneficiarioListView.as_view(), name = 'listado_beneficiario'),
    path( 'beneficiario/detalle/<int:pk>', beneficiarioDetailView.as_view(), name = 'detalle_beneficiario'),

]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register

    # ADD NEW Routes HERE
    re_path('chaining/', include('smart_selects.urls')),

    path("personas/", include("apps.persona.urls")),
    path("electro/", include("apps.electrodependientes.urls")),
    path("inventario/", include("apps.inventario.urls")),
    path("productos/", include("apps.productos.urls")),

    # Leave `Home.Urls` as last the last line
    path("", include("apps.home.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/templates/electro/medico/listado.html
{% extends 'layouts/base2.html' %}

{% block stylesheets %}
    <link type="text/css" href="{{ ASSETS_ROOT }}/css/custom.css" rel="stylesheet">
{% endblock stylesheets %}

{% block title %}{{title}}{% endblock %}

{% block content %}

    <!-- Modal -->
    <div class="modal fade m-modal-7" id="medico_filter" tabindex="-1" role="dialog" aria-labelledby="medico_filterTitle" aria-hidden="true">
        <div class="modal-dialog modal-xl modal-dialog-centered" role="document">
            <div class="modal-content">

                <div class="modal-header bg-gris">
                    <h5 class="modal-title" id="exampleModalLongTitle">Filtrar por:</h5>
                </div>

                <form id="filter_form" method="GET" action="{% url 'electrodependientes:listado_medico' %}">
                    <div class="modal-body">

                        404

                        {% comment %}
                        <div class="row align-items-end mb-3">

                            <div class="form-group col">
                                {{ filter_form.articulo.label_tag}}
                                {{ filter_form.articulo}}
                            </div>
                            <div class="form-group col">
                                {{ filter_form.situacion.label_tag}}
                                {{ filter_form.situacion}}
                            </div>
                            <div class="form-group col">
                                {{ filter_form.sucursal.label_tag}}
                                {{ filter_form.sucursal}}
                            </div>
                        </div>
                        <div class="row align-items-end mb-3">
                            <div class="form-group col">
                                {{ filter_form.estado.label_tag}}
                                {{ filter_form.estado}}
                            </div>
                            <div class="form-group col">
                                {{ filter_form.marca.label_tag}}
                                {{ filter_form.marca}}
                            </div>
                            <div class="form-group col">
                                {{ filter_form.origen.label_tag}}
                                {{ filter_form.origen}}
                            </div>
                        </div>
                        <div class="row">
                            <div class="mb-3 col">
                                <div class="d-flex justify-content-center">
                                    <div>
                                        <label for="valor">Valor:</label>

                                        <input type="text" disabled hidden id="valor" name="valor-range"/>
                                        <input type="text" disabled id="valor-text" style="border: 0; color: #f6931f; font-weight: bold;" />

                                        <div id="valor-range" style="width:450px;"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="mb-3 col">
                                <div class="d-flex justify-content-center">
                                    <div>
                                        <label for="modelo">Modelo:</label>
                                        <input type="text" disabled hidden id="modelo" name="modelo-range"/>
                                        <input type="text" disabled id="modelo-text" name="" style="border: 0; color: #f6931f; font-weight: bold;" />
                                        <div id="modelo-range" style="width:450px;"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endcomment %}

                    </div>
                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn border border-danger text-danger" data-bs-dismiss="modal">Cancelar</button>
                        <div>
                            <button id="borrar_filtros" type="button" class="btn border-orange me-2">Borrar filtros</button>
                            <button name="filter" value="true" type="submit" class="btn bg-orange text-white">Aplicar filtros</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Table -->
    <div class="card border-0 shadow-table my-4">

        <div class="card-header d-flex flex-direction-row justify-content-between bg-gris">
            <h5 class="my-auto">{{title}}</h5>

                <div class="d-flex flex-direction-row justify-content-between">

                    <form method="GET" class="me-3" action="{% url 'electrodependientes:listado_medico' %}">
                        <div class="input-group">
                            <input type="number" required class="form-control" id="exampleInputIconRight" name="search" placeholder="Buscar documento" aria-label="Buscar documento">
                            <button type="submit" class="input-group-text bg-orange" id="basic-addon2"><i class="fa fa-search text-white" aria-hidden="true"></i></a href="#"></button>
                        </div>
                    </form>

                    {% comment %} <button class="btn bg-orange text-white me-3" type="button" data-bs-toggle="modal" data-bs-target="#medico_filter" aria-expanded="false" aria-controls="medico_filter">
                        Filtrar
                    </button> {% endcomment %}

                    {% if perms.electrodependientes.add_medico%}

                        <a href="{% url 'electrodependientes:registrar_medico' %}">
                            <button class="btn bg-success text-white" type="button" title="Registrar medico">
                                Registrar
                            </button>
                        </a>
                    {% endif %}
                </div>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-centered table-nowrap mb-0 rounded">

                    <thead class="thead-light">
                        <tr>
                            <th class="border-0 rounded-start">Nombre</th>
                            <th class="border-0">Apellido</th>
                            <th class="border-0">Documento</th>
                            <th class="border-0">Matricula profesional</th>
                            <th class="border-0">Usuario creador</th>
                        </tr>
                    </thead>

                    <tbody>

                        {% for electro in object_list %}
                        <!-- Item -->
                        <tr>
                            <td>
                                {{electro.nombre}}
                            </td>
                            <td>
                                {{electro.apellido}}
                            </td>
                            <td>
                                {{electro.documento}}
                            </td>
                            <td>
                                {{electro.matricula_profesional}}
                            </td>
                            <td>
                                {{electro.usuario_creador}}
                            </td>
                        </tr>

                        {% empty %}

                            <tr style="line-height: 4rem;">
                                <td colspan="8" class="text-center">Sin resultados</td>
                            </tr>

                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center li-hover mb-0">

            <li class="page-item">
                <a class="page-link" href="{{url}}page=1" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">First</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="{{url}}page={% if page_obj.has_previous %}{{ page_obj.previous_page_number }}{% endif %}" aria-label="Previous">
                <span aria-hidden="true">&lsaquo;</span>
                <span class="sr-only">Previous</span>
                </a>
            </li>

            {% for i in page_obj.paginator.page_range %}
                <li class="page-item">
                    <a class="page-link {% if page_obj.number == i %}bg-orange text-white{% endif %}" href="{{url}}page={{ i }}">{{i}}</a>
                </li>
            {% endfor %}

            <li class="page-item">
                <a class="page-link" href="{{url}}page={% if page_obj.has_next %}{{ page_obj.next_page_number }}{% endif %}" aria-label="Next">
                <span aria-hidden="true">&rsaquo;</span>
                <span class="sr-only">Next</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="{{url}}page={% if page_obj.has_next %}{{ page_obj.paginator.num_pages }}{% endif %}" aria-label="Previous">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Last</span>
                </a>
            </li>
        </ul>
    </nav>



{% endblock content %}

{% block javascripts %}
{% endblock javascripts %}

apps/templates/electro/medico/registrar.html
{% extends 'layouts/base2.html' %}

{% block stylesheets %}
    <link type="text/css" href="{{ ASSETS_ROOT }}/css/custom.css" rel="stylesheet">
{% endblock stylesheets %}

{% block title %}{{title}}{% endblock %}

{% block content %}

    <h4 class="py-4 my-2 ps-0">{{title}}</h4>

    <form id="form" method="POST" enctype="multipart/form-data">

        <!-- Security token -->
        {% csrf_token %}

        <div class="card border-0 shadow-table border-bottom mb-4">

            <div class="card-header bg-gris">
                <h6 class="my-1">Datos personales:</h6>
            </div>

            <div class="card-body border-0">

                {{ medico.usuario_creador}}

                <div class="row align-items-end mb-3">
                    <div class="form-group col">
                        {{ medico.nombre.errors}}
                        {{ medico.nombre.label_tag}}
                        {{ medico.nombre}}
                    </div>
                    <div class="form-group col">
                        {{ medico.apellido.errors}}
                        {{ medico.apellido.label_tag}}
                        {{ medico.apellido}}
                    </div>
                </div>

                <div class="row align-items-end mb-3">
                    <div class="form-group col">
                        {{ medico.documento.errors}}
                        {{ medico.documento.label_tag}}
                        {{ medico.documento}}
                    </div>
                    <div class="form-group col">
                        {{ medico.matricula_profesional.errors}}
                        {{ medico.matricula_profesional.label_tag}}
                        {{ medico.matricula_profesional}}
                    </div>
                </div>
            </div>
        </div>

        <div class="card border-0 shadow-table border-bottom mb-4">

            <div class="card-header bg-gris">
                <h6 class="my-1">Datos de contacto:</h6>
            </div>

            <div class="card-body border-0">

                <div class="row align-items-end mb-3">
                    <div class="form-group col-2">
                        {{ medico.codigo_area_c.errors}}
                        {{ medico.codigo_area_c.label_tag}}
                        {{ medico.codigo_area_c}}
                    </div>
                    <div class="form-group col">
                        {{ medico.numero_telefono_c.errors}}
                        {{ medico.numero_telefono_c.label_tag}}
                        {{ medico.numero_telefono_c}}
                    </div>
                    <div class="form-group col-2">
                        {{ medico.codigo_area_f.errors}}
                        {{ medico.codigo_area_f.label_tag}}
                        {{ medico.codigo_area_f}}
                    </div>
                    <div class="form-group col">
                        {{ medico.numero_telefono_f.errors}}
                        {{ medico.numero_telefono_f.label_tag}}
                        {{ medico.numero_telefono_f}}
                    </div>
                </div>

                <div class="row align-items-end mb-3">
                    <div class="form-group col">
                        {{ medico.email.errors}}
                        {{ medico.email.label_tag}}
                        {{ medico.email}}
                    </div>
                </div>
            </div>
        </div>

        <input type="submit" name="confirmar" value="Confirmar" class="btn btn-success text-white">
    </form>

{% endblock content %}

{% block javascripts %}

    <script>

        // Select2 para buscador en select

        $(document).ready(function() {

            $('#id_persona_electrodependiente').select2({
                debug: true,
                placeholder: 'Buscar persona',
                selectionCssClass: 'h-select',
                allowClear: true,
                escapeMarkup: function (markup) { return markup; },
                language: {
                    noResults: function () {

                        return "<a href='{% url 'persona:registrar_persona' %}'>Sin resultados - Agregar nueva persona</a>";
                    }
                }
            });

            $('#id_titulardesuministro_set-0-titular_servicio').select2({
                language: 'es',
                placeholder: 'Buscar persona',
                selectionCssClass: 'h-select',
                allowClear: true,
                escapeMarkup: function (markup) { return markup; },
                language: {
                    noResults: function () {

                        return "<a href='{% url 'persona:registrar_persona' %}'>Sin resultados - Agregar nueva persona</a>";
                    }
                }
            });

            $('#id_diagnostico_set-0-medico').select2({
                language: 'es',
                placeholder: 'Buscar medico',
                selectionCssClass: 'h-select',
                allowClear: true,
                escapeMarkup: function (markup) { return markup; },
                language: {
                    noResults: function () {

                        return "<a href='{% url 'persona:registrar_persona' %}'>Sin resultados - Agregar médico</a>";
                    }
                }
            });

        });
    </script>

    <script>

        document.addEventListener("DOMContentLoaded", function(event) {

            const cud = document.getElementById("id_cud");
            const fecha_cud = document.getElementById("id_fecha_vencimiento_cud");

            if(cud){
                cud.addEventListener("change", mostrarFecha);
            }

            function mostrarFecha(){

                if(cud.value === 'True'){
                    fecha_cud.removeAttribute("disabled");
                }
                else{
                    fecha_cud.value = ('');
                    fecha_cud.setAttribute("disabled", true);
                }

            }

        });

    </script>

{% endblock javascripts %}